### ISSUE TITLE
Why not use UTXO model but balance model?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#100]
In the v systems, the code uses the balance model instead of the UTXO model to calculate the MAB, I wonder to know why and I give a basic design about coin age based on the UTXO model corresponding to the design about coin age based on the Balance model. And I am willing to get feedbacks from you for any suggestion.
The design about coin age based on the UTXO model as follows:
Each utxo in a different block height has different price which is less than or equal to its actual price and an utxo will be equal to its own price when undergoing N blocks(sliding windows). 
Formulation is that MAB = min{Balance_currentHeight, sum(alpha*utxo_i)} where alpha is equal to (current_height - height_i) / N if current_height - height_i < N, else alpha is equal to 1.

**Comment by eunoodle** [comment]
Hi @ToWorld , thank you for reaching out. Our team is currently working hard to improve the usability of V SYSTEMS, and we highly appreciate any feedback you can provide to contribute to the development of the network. 

If you are interested in providing feedback and working more closely with our team to improve V SYSTEMS for developers, you can send our developer relations team an email at developers@v.systems. We look forward to hearing from you. 

Thanks,
V SYSTEMS Team

**Comment by zl730** [comment]
There are lots of articles on internet comparing utxo and account model. And i think we prefer the efficiency of account model.
