### ISSUE TITLE
The account recovered with the seed key is different from the original account.

### ISSUE THREAD

**Issue by qkrwnsgh1288** [virtualeconomy/v-systems#102]
```
$ curl -X GET --header 'Accept: application/json' --header 'api_key:  aaa' 'http://192.168.56.11:9922/addresses/seed/ATyV1x1wPE9fLPMYWQzC3Aco3bkxiof4fsf'
{
  "address" : "ATyV1x1wPE9fLPMYWQzC3Aco3bkxiof4fsf", // origin address
  "seed" : "22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff" //seed same
}
$
$ java -jar walletgenerator_v0.1.0.jar -k "22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff" -t -p 1111
------------------------------------------------------------------------------------------------------------------------------------------------------
IMPORTANT - COPY OR MEMORIZE THE SEED PHRASE BELOW FOR KEY RECOVERY!!!
seed         : 22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff //seed same
------------------------------------------------------------------------------------------------------------------------------------------------------
address #    : 0
address      : ATwjHRGw3k6snCG4Kmf2EMgp49xegGLTNpH  // different address (?)
public key   : 9YrMh2ePVPq97EbEadAvr3qbB9e3wJZpCzJqRohZoxja
private key  : Dz96W9ZtBMsB1zAZe4cy7c4pLCuabegTZViMrTLz8g2M
account seed : CQFKGEXHkVsWBmw3KkBrJuM79fQEMGPEeD7xqnYQp5Z6
------------------------------------------------------------------------------------------------------------------------------------------------------
```
In the testnet, 
I got seed "22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff" from address "ATyV1x1wPE9fLPMYWQzC3Aco3bkxiof4fsf"
And, I recoverd my address from seed "ATyV1x1wPE9fLPMYWQzC3Aco3bkxiof4fsf".
But I got different address "ATwjHRGw3k6snCG4Kmf2EMgp49xegGLTNpH" 

What did I do wrong??

**Comment by ncying** [comment]
The seed from `/addresses/seed/{address}` is encoded by `Base58`. That is the key why the two 'seed' is different.

Since the node only has one wallet. I suggest to use `/wallet/seed` to get the seed(1. original one, 2. not encoded by `Base58` and 3. can be used in wallet generator directly)

**Comment by qkrwnsgh1288** [comment]
Okay. I will use `/wallet/seed`. 
But I want to know to use `/addresses/seed/{address}` so, I tried decoding `22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff` to base58. But the result is `^FD¬ì©}6Z!!Ò"qô{ihÇ«Þgu¯V`. When I use the walletgenerater, in `-k` option, I didn't get the decoded seed.

And... When I tried `/wallet/seed`,
```
$ curl -X GET --header 'Accept: application/json' --header 'api_key:  sdf' 'http://192.168.56.11:9922/wallet/seed'
{
  "seed" : "59yeG9BDqvkTkL3YEQg8wrtZMR5HBFnKvxHnyBWMxw43Gt7FBMpMpPZgCkPES4FfZYUWWJhEvt3yfkehN7eH3cQs"
}
$
$ java -jar walletgenerator_v0.1.0.jar -k "59yeG9BDqvkTkL3YEQg8wrtZMR5HBFnKvxHnyBWMxw43Gt7FBMpMpPZgCkPES4FfZYUWWJhEvt3yfkehN7eH3cQs" -t -p 1111
------------------------------------------------------------------------------------------------------------------------------------------------------
IMPORTANT - COPY OR MEMORIZE THE SEED PHRASE BELOW FOR KEY RECOVERY!!!
seed         : 59yeG9BDqvkTkL3YEQg8wrtZMR5HBFnKvxHnyBWMxw43Gt7FBMpMpPZgCkPES4FfZYUWWJhEvt3yfkehN7eH3cQs
------------------------------------------------------------------------------------------------------------------------------------------------------
address #    : 0
address      : AUCwxguYDENfx3dqhQXELQGwNeTe5r5nnTQ
public key   : E3FQuVvUdkp9PagDeD9LrLNb3gQb6PCcKfaTujMNiFtn
private key  : 5ttFfmt5zWLmFDQ7yLJkm1xdyFATEzJ2wCHyZeQNMuzi
account seed : 51FfJr4E2eTbgfU7xzKZubFWDjYNv3e3WTQsok2vJUE5
------------------------------------------------------------------------------------------------------------------------------------------------------
```
It is different too...

**Comment by ncying** [comment]
In addition, `/addresses/seed/{address}` will get the "seed" of the related address. We call it `accountSeed` in the systems.
```scala
accountSeed = SecureCryptographicHash((nonce.toString + seed).getBytes("UTF-8")) 
//Array[Byte], need to use Base58 to encode
//to get "22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff" in your case
```
where in `nonce` is the index from `0`, and `seed` is the correct seed which used in wallet generator(generate the whole wallet).

In you case, you get  the `accountSeed` form the API. Then you need an inverse of `SecureCryptographicHash` to get the hidden seed. That's an "impossible" work. And this is also the proof that one of you private key/accountSeed lost, it will not affect too much to you wallet's seed.

**Comment by qkrwnsgh1288** [comment]
That means it is impossible to recover account by using accountSeed(`22zVZ6FL4dZJCiY5HXXX8c8wV5tVriDhMaSqjFock4ff`). That's right??
if not, how is it used for recovery?

**Comment by ncying** [comment]
here is the basic concept.

seed => accountSeed => private key => public key => address.

So if you have accountSeed, you can recover **one** related address’s private key. But you can not/hard to get the inverse of hash to recover the seed.

seed is higher level than accountSeed. It can generate series of accountSeed.

**Comment by qkrwnsgh1288** [comment]
Okay. Thank you for your kind answer!!
