### ISSUE TITLE
Where to get a contract code and how to run it?

### ISSUE THREAD

**Issue by gigawarrior** [virtualeconomy/v-systems#105]
I've read the Sample Code for Smart Contract in the wiki here: https://github.com/virtualeconomy/pyvsystems/wiki/Sample-Code-for-Smart-Contract . In order to run the Smart Contract, I switched the branch to testExecuteContract. However, when running the test_register_contract, I found that the contract_permitted function returned None, which cause the contract None, leading to an error when called the  subsequent register_contract function. Where can I get a template or code of the contract so that I can register then excute it successfully?

**Comment by SheldonYS** [comment]
duplicated issue in https://github.com/virtualeconomy/pyvsystems/issues/10
