### ISSUE TITLE
what's the api address to get the public network chain current height?

### ISSUE THREAD

**Issue by jumper-ning** [virtualeconomy/v-systems#111]
what's the api address to get the public network chain current height?Is there any documents about this?

**Comment by hvoid-build-block** [comment]
One way to do this is to start a node with the following command after downloading the source code:
sbt vsys-mainnet.conf

Remenber to set directory path in conf file. And the api-key-hash value should use the secure hash function under the utils of the api webpage. This key is for using account, transaction and etc on the api webpage.

**Comment by faddat** [comment]
If we don't hear back from this user soon, we should probably close this issue.
