### ISSUE TITLE
Consolidation of documentation

### ISSUE THREAD

**Issue by faddat** [virtualeconomy/v-systems#132]
Currently, we have documentation in several repositories and a wiki, but not versioned alongside the code.  In order to make VSYS more attractive to both power users and developers, we should establish a single set of documentation in this repository https://github.com/virtualeconomy/v-systems/

This way, when users do like:

```
git clone https://github.com/virtualeconomy/v-systems
```

They also get our latest documentation.  By keeping our documentation here (only) as opposed to in multiple locations, we can ensure that documentation on our web site is always generated from our very freshest docs that match the latest version of the VSYS software.

**Comment by ncying** [comment]
@faddat I think we will not add documentation directly in the repo. we can prepare a detail and well organized wiki and add a link in README.
