### ISSUE TITLE
Node cannot restart after calling POST /debug/rollbak endpoint

### ISSUE THREAD

**Issue by kwunyeung** [virtualeconomy/v-systems#157]
I am running a super node on testnet. It seems that the node is validating on a fork. I tried to make a call to `/debug/rollback`. The node got panic 

```
Oct 28 09:07:32 vsys-validator vsys[30253]: terminate called after throwing an instance of 'std::bad_alloc'
Oct 28 09:07:32 vsys-validator vsys[30253]:   what():  std::bad_alloc
```
And it can't be restarted again. I think the DB is corrupted.

**Comment by faddat** [comment]
Thanks for the report!

**Comment by zl730** [comment]
`std::bad_alloc` is an insufficient memory issue. Try to remove the data and restart the node.
