### ISSUE TITLE
setSlotAddress function

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-systems#16]
`setSlotAddress` function should release the `address->id` connection first

**Comment by hiutin0** [comment]
After careful testing, I have found that the original setSlotAddress function should be OK. 

The fact is that when address->id exists, the MVMap will remove the existing information first and then add the key and the corresponding value. Detailed information can be found at Map.java for the *put* function [Removes the mapping for a key from this map if it is present.]

**Comment by hiutin0** [comment]
The exiting setSlotAddress didn't update the Map called `addressToID', which is `address -> slotId'. If the Map keeps the old information of `address -> slotId', when we want the address (which was beat last time but still kept in the database) to re-contend a slotId, there is an error of an address contending multiple slotIds.
