### ISSUE TITLE
Amount in testexplorer.v.systems is not correct

### ISSUE THREAD

**Issue by rogercarter1** [virtualeconomy/v-systems#163]
Here is the url.
https://testexplorer.v.systems/transactions/FXH75AaW8xWnsM4dwEzWUNpitV8zAfVSX7DB9EPRC8rf

I only transfer 0.00000001 vsys, but it says i transfer 1 vsys.

**Comment by SheldonYS** [comment]
We have just fixed this issue. Please retry. Thanks for your feedback!
