### ISSUE TITLE
Can not report issue to https://github.com/virtualeconomy/go-v-sdk

### ISSUE THREAD

**Issue by rogercarter1** [virtualeconomy/v-systems#164]
Where should I report issues to https://github.com/virtualeconomy/go-v-sdk ? here? Please document how to report issue in https://github.com/virtualeconomy/go-v-sdk/blob/master/README.md

**Comment by SheldonYS** [comment]
Please report issue here https://github.com/walkbean/vsys-sdk-go/issues
