### ISSUE TITLE
Bug in go-v-sdk IsValidateAddress

### ISSUE THREAD

**Issue by rogercarter1** [virtualeconomy/v-systems#165]
https://github.com/virtualeconomy/go-v-sdk/blob/master/vsys/common.go#L32

This line 
```
if data[0] != addrVersion && data[1] != byte(network) {
```
should be:
```
if data[0] != addrVersion || data[1] != byte(network) {
```

IsValidateAddress do not check TestNet or MainNet in the address.

**Comment by SheldonYS** [comment]
fixed by https://github.com/virtualeconomy/go-v-sdk/commit/deb82f7a1cb527ae61350b3dd1962afac1c58005
