### ISSUE TITLE
Fix or Stop shipping .Deb files

### ISSUE THREAD

**Issue by faddat** [virtualeconomy/v-systems#211]
Because there are known issues with the configuration implemented with the .Deb files, we should stop shipping them or implement our known-good configuration in them.

Issue with deb files mentioned in #194

**Comment by ncying** [comment]
.Deb file works well for most of the machines in test and most of the node maintainers used the .Deb file well in their usage. So, we still need to release this version for users. But for your cases, I add some suggestions for users, but these suggestions are not necessary for all .Deb file users.

**Comment by faddat** [comment]
#210 

#218 

#194 

The conversation in those issues has frequently mentioned the deb files as a source of potential instability. are the deb files a source of potential instability?

If no, and it is perfectly acceptable for the default deploy path to be the deb files, then let's close this issue. If not, let's fix or stop shipping the debs files.

**Comment by ncying** [comment]
No.
.deb file should be fine in most situations. In the current test, if it arranged with more system resources, it should be fine. In the later version, we will refactor some dynamic variable usages and make it more stable in more lower system resource situations.

**Comment by faddat** [comment]
OK.  

Do we have a canonical "system requirements" spec?

I can add this to documentation.  

Currently it seems to me that we have
