### ISSUE TITLE
How to convert seed into seed words?

### ISSUE THREAD

**Issue by YaakovHuang** [virtualeconomy/v-systems#49]
I am accessing the vsys recharge. My node only generate seed(http://<node_ip>:9922/wallet/seed), not seed words, so I want to know if the official has provided a way to convert the seed into a seed word.   I want to restore the wallet through v wallet. I found that v wallet only supports seed words. Does not support seed (private key).

**Comment by ncying** [comment]
you can use
[v-wallet-generator](https://github.com/virtualeconomy/v-wallet-generator)
or
[pyvsystems](https://github.com/virtualeconomy/pyvsystems)
to recover the private key from the seed.

finally, you can also run v-systems's scala command line to recover the private key from the seed.

but, I does suggest to generate an important seed randomly from fullnode (hot online). Incline to generate the seed by using a cold wallet or tools like [pyvsystems](https://github.com/virtualeconomy/pyvsystems) and [v-wallet-generator](https://github.com/virtualeconomy/v-wallet-generator) offline.

**Comment by faddat** [comment]
Seems we have resolve this issue and should close it.
