### ISSUE TITLE
分配收益时间

### ISSUE THREAD

**Issue by BigOceanGG** [virtualeconomy/v-systems#57]
在抵押挖矿后，什么时候能够有收益，马上就有收益吗？

**Comment by ncying** [comment]
Q: Whem can we get the reward after using `minting` in V Systems?

A: 
Two cases.
i. if you are one of super-node, you can get the reward directly after you contend and mint a block successfully.

ii. if you are one of customer who only leases your VSYS coin to the super-node. 
a. base on the current rules, super-nodes own the right to separate their total reward. daily, weekly and monthly are all potential choices. 
b. you should talk with the particular super-node which you trust/lease for the detail reward time and rules.

Finally, if you find any problem, please report the detail here.

**Comment by BigOceanGG** [comment]
如果我申请成为超级节点，可以自由决定分配收益的时间吗？需要写合约吗？

**Comment by ncying** [comment]
Q1: I am one of super-node, can I decide the reward arrangement time?
yes

Q2: should I need a contract?
in the current version, no

However, it needs some basic requirements to be a super-node. please contact the team for more detail information.

**ALL** detail contact information can be found in the project [website](https://www.v.systems).

Welcome to the V Systems community.

**Comment by BigOceanGG** [comment]
没在官网上找到联系信息，有相关方面的微信吗？大陆这边没法上Facebook等，能发个联系方式吗？

**Comment by BigOceanGG** [comment]
申请成为超节点的要求我知道了，应该至少大于100万个vsys。我想知道成为超节点后，是通过抵押到本超级节点的vsys自由计算返还的比例，然后手动给抵押账户转账吗？

**Comment by BigOceanGG** [comment]
vsys支持合约吗？如果不支持合约，那不是要手动发放收益？

**Comment by ncying** [comment]
Q1: About the contact information?
You can email to the `info` or `bd` team or join the fans telegram. All detail email and information can be found on the project website.

Q2: Contract in V Systems?
As I answered before, in the current version, no. but we will start to support some contracts in the near future.

Q3: Contract for reward separation?
Sorry, I think base on the security issue, we will not suggest separating the reward by contract.
**Here is the important information you should know.**
V Systems support cold minting. Which means that your `mint account` can be different from your `reward account`. If your `reward account` is an account in a cold wallet, and auto reward separating by a contract will degrade the security level.

I think you can contact the team or get more information from the community about how to maintain a super-node in V Systems. And I think you can get more **smart ideas**.

Finally, as I know 
1. different super-node team has their own rule/game to separate their reward.
2. it seems that they also designed many tools to help them finish the separating tasks.
3. they are third-party tools base on the V Systems main chain, and I has no extra information about them. However, we wish our systems can be more powerful in the future and provide the users more stuff to **play**.

Let's re-architect the blockchain.

**Comment by JZCherise** [comment]
> 在抵押挖矿后，什么时候能够有收益，马上就有收益吗？

我们是VPower节点官方，你可以联系我来解决你的问题：）

**Comment by JZCherise** [comment]
> 在抵押挖矿后，什么时候能够有收益，马上就有收益吗？



> 没在官网上找到联系信息，有相关方面的微信吗？大陆这边没法上Facebook等，能发个联系方式吗？

请加VPower节点微信：btc123cx
