### ISSUE TITLE
vsys 0.1.1 has some data in /root/.vsys/data

### ISSUE THREAD

**Issue by lcgogo** [virtualeconomy/v-systems#59]
vsys 0.1.1 docker image stores some data in /root/.vsys/data when I set the path as /data/vsys in vsys.conf like below

vsys {
  # Path Settings
  directory = /data/vsys

docker exec -it vsys-0.1.1 /bin/sh
/ # cd /root/.vsys/data/
~/.vsys/data # ls -l
total 1871020
-rw-r--r--    1 root     root       2112645 Apr  9 03:49 000035.sst

**Comment by ncying** [comment]
you should follow the `vsys-testnet.conf` to set your data path.

`directory` is the wallet related path
and 
`data-directory` is the path of levelDB data

**Comment by ncying** [comment]
@zl730

**Comment by lcgogo** [comment]
got it, it's a little confused and not update in mainnet conf.

**Comment by ncying** [comment]
yes. but the current release is only for Testnet. and it will be update later~
