### ISSUE TITLE
Does vsys have gas fees?

### ISSUE THREAD

**Issue by BigOceanGG** [virtualeconomy/v-systems#62]
If have gas fees，then what is it？

**Comment by ncying** [comment]
No. There is no gas fee concept in current systems. All transaction fee will be calculated by VSYS coin.

Moreover, in the V Systems economy, all transaction fee will be destroyed. Compare with most of the other ecosystems, miners get the transaction fee, this policy means all transaction fee will be returned to all users in this system. In other words, it reduces the total inflation.

**Comment by BigOceanGG** [comment]
That is to say, transaction fees should be exist, but the fees will not reach the miners, but evaporate directly.

**Comment by Gbolly1151** [comment]
> No. There is no gas fee concept in current systems. All transaction fee will be calculated by VSYS coin.
> 
> Moreover, in the V Systems economy,  **all transaction fee will be destroyed**. Compare with most of the other ecosystems, **miners get the transaction fee**, this policy means **all transaction fee will be returned to all users in this system**. In other words, it reduces the total inflation.


You have conflicting statements here

1.all transaction fee will be destroyed
2.miners get the transaction fee
3.all transaction fee will be returned to all users in this system

If transaction fees are destroyed how it is possible for miners to get transaction fees and how are destroyed fees gotten back to users in the system

**Comment by faddat** [comment]
In v.systems, transaction fees are burned

In most other blockchain ecosystems, miners or validators get the transaction fees.

We should probably close this issue.
