### ISSUE TITLE
How to keep the system move on healthily when all super nodes are killed?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#91]
Here is the case:
    There are two kinds of super nodes, super nodes to mint and candidate nodes. When all super nodes are killed unfortunately, how to keep the whole system move on?

**Comment by ncying** [comment]
If there is one super-node alive, then the candidate nodes can use contend transaction to replace the one which is suspended.

If all super-nodes `dead`(all related minters' private keys missed, and no one can add new data to the chain), this is a low probability case, then the whole blockchain will be stopped. However, this does not mean that the whole blockchain `dead` forever. The community can update the consensus(e.g. create templated minter) and continue the chain. 

The situation above is the first level attack, the solution should as same as a hard fork.

**Comment by ToWorld** [comment]
Thanks a lot. I have two extra questions based on the answer above:
1."If there is one super-node alive, then the candidate nodes can use contend transaction to replace the one which is suspended."  --> You said that the only one super-node has been suspended, there was no any super node to mint, therefore, how to post a contend transaction to replace the sick super-node?
2.How to avoid the case where all super nodes resist a kind of transactions such as contend transactions?

**Comment by ncying** [comment]
0. It is better to use "replace other minters/super-node". Which means the alive one is still a `good` super-node

1. This is still the first level attack, it is the case equal even heavier than 51% attack. SPoS consensus can not avoid fork, but users in the community will choose which fork they trust.

**Comment by ToWorld** [comment]
Thanks a lot. There is a final question:
How to resist the attack of 51%?

**Comment by ncying** [comment]
There are no common answers to this question.

From my personal idea, 
1. the difference between PoW and PoS to handle the 51% attack is computing power and staking. In the current situation, no one can guarantee that which one is better. One important evidence which supports the staking is that staking is highly correlating with the chain economy values. One use 51% staking attack actually harms the attacker itself. Base on the elemental theory in game theory, such action is irrational. 
2. Back to SPoS, it gives more extra features to avoid the 51% attack. For example, the design of minting average balance, the cold minting architecture, and the super-node contend conditions, etc, can reduce the probability of 51% attack. You can check the white paper of SPoS to get more detail information.

**Comment by ToWorld** [comment]
Thanks a lot.
