### ISSUE TITLE
Is the contend fee burnt even if the contender fails to contend?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#95]
I found that even if the contender failed to content, the contend fee was burnt still in the file of ContendSlotsTransactionDiff.scala.
Could you tell me the reason for such design?

**Comment by ncying** [comment]
To avoid the high frequency attack. So candidate node should make sure all two conditions satisfied (1. MAB > the exist slot node 2. at least 1M VSYS lease in or balance, named effective balance) before contend.

**Comment by ToWorld** [comment]
It means that If I failed to contend, I had to pay the contend fee(for about 50000VSYS) which was burnt later.
Right?

**Comment by ncying** [comment]
Yes. All transaction fee, including contend transaction fee, will be destroyed immediately.

**Comment by ToWorld** [comment]
If all transaction fee will be destroyed, It is a best scheme to generate an empty block for super node.
Right?

**Comment by ncying** [comment]
No, destroy transaction fee will reduce the total inflation. This is good to all users including the super-node itself.

Anyway, one can generate an empty block, but as I mention in #92, if super-node does `harmful actions`, it will be contended easier.

**Comment by ToWorld** [comment]
Thank you, I got it.
