### ISSUE TITLE
Is that right that the formulation of MAB is same as the coin age?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#97]
I find that MAB means you need to accumulate the coin age. For example, 1 coin in the old block height is more expensive than 1 coin in the new block height. The invocation of SPos I think is that the VSYS introduces the concept of super nodes and common people with less money can also get  block rewards by the way of leasing out their coins.
Right? Or can you tell me more?

**Comment by ncying** [comment]
The answer for the title question is "NO".

MAB is similar to coin age, but actually they are two different stats. In general `1 coin in the old block height is more expensive than 1 coin in the new block height.` this is incorrect. In a small period, coins in older block will cumulate more MAB. But after 86400blocks, MAB will equal to the coin number.

Please check the detail in the [white paper](https://www.v.systems/pdf/sposwhitepaper.pdf).

**Comment by ToWorld** [comment]
Yes, finally 1 coin is equal to 1 coin.

**Comment by ToWorld** [comment]
Why spos treats someone's own coins as same as coins leasing in? I mean that if it is ok that coins leasing in is cheaper than someone's own coin?

**Comment by ncying** [comment]
Just my personal understanding. I think one coin should own the same right in consensus, no matter where the coin come from. 

I can not agree that `coins leasing in is cheaper than someone's own coins`. How to get more lease in is still an open question for super-node owns.

**Comment by ToWorld** [comment]
Yes, I can't agree with you more.
