### ISSUE TITLE
What difference between fee and feeScale in the code?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#98]
What difference between fee and feeScale in the code?

**Comment by ncying** [comment]
In the current system, `fee` is a fixed number charged by the system. And `feeScale` is a constant 100.

But this is some pre-setting which used to design a more flexibility fee-charging model for the more complex system operations. A general framework is already designed and implemented. But it should be embedded with other system tools. The detail design scheme is proposed, but it is not an open source now. Any good suggestion is welcome.

**Comment by ToWorld** [comment]
Can you give more details about the fee design?

**Comment by ncying** [comment]
For the current stage, a fixed fee design is good for the system(all the system operation is predictable).

For the flexibility fee-charging model, sorry, I can not give more information about the design part now.

**Comment by ToWorld** [comment]
Do you have wechat?
